In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import  LinearRegression

In [2]:
#. Predicting House Prices
#●	Input: Size of the house in square feet, number of bedrooms.
#●	Output: Predicted price of the house

size = np.array([800,1000,1200,1400,1600]).reshape(-1,1)
prices =np.array([15000,20000,25000,28000,30000])

In [9]:
model = LinearRegression()

In [10]:
model

LinearRegression()

In [11]:
model.fit(size,prices)

LinearRegression()

In [12]:
prediction_value = np.array([[1800]])

In [15]:
prediction_price = model.predict(prediction_value)

In [16]:
prediction_price

array([35000.])

In [25]:
#Predicting Salary Based on Years of Experience
#●	Input: Years of work experience.
#	Output: Predicted salary.
year_of_experience = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(-1,1)
salary = np.array([10000,15000,18000,25000,28000,30000,35000,38000,40000,45000])

In [26]:
model =LinearRegression()

In [27]:
model

LinearRegression()

In [28]:
model.fit(year_of_experience,salary)

LinearRegression()

In [29]:
prediction_experience=np.array([[5]])

In [30]:
prediction_salary = model.predict(prediction_experience)

In [31]:
prediction_salary

array([30284.84848485])

In [33]:
#. Predicting Car Prices
#●	Input: Age of the car, mileage.
#●	Output: Predicted resale price of the car.
age = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
Price_of_car = np.array([100000,150000,180000,250000,280000,300000,350000,380000,400000,450000])


In [34]:
model=LinearRegression()

In [35]:
model.fit(age,Price_of_car)

LinearRegression()

In [36]:
model

LinearRegression()

In [37]:
prediction_car_age = np.array([[9]])

In [38]:
prediction_car_resale_price = model.predict(prediction_car_age)

In [39]:
prediction_car_resale_price

array([415939.39393939])

In [40]:
#. Predicting Student Scores
#●	Input: Hours studied, number of practice tests taken.
#●	Output: Predicted exam score.
hours_studied = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
exam_score = np.array([100,150,180,250,280,300,350,380,400,450])


In [41]:
model = LinearRegression()

In [42]:
model

LinearRegression()

In [43]:
model.fit(hours_studied,exam_score)

LinearRegression()

In [50]:
prediction__hours_studied = np.array([[8]])

In [51]:
prediction_exam_score = model.predict(prediction__hours_studied)

In [52]:
prediction_exam_score

array([378.24242424])

In [57]:
#Predicting Rent Prices
#●	Input: Size of the apartment in square feet, number of bedrooms, location rating.
#●	Output: Predicted rent price.
square_feet = np.array([400,800,1200,1500,1800,2000,2200,2800,3000]).reshape(-1,1)
rent_room = np.array([10000,15000,18000,23000,25000,28000,32000,35000,38000])

In [58]:
model=LinearRegression()

In [59]:
model

LinearRegression()

In [60]:
model.fit(square_feet,rent_room)

LinearRegression()

In [61]:
model

LinearRegression()

In [62]:
prediction_square_feet = np.array([[1500]])

In [63]:
prediction_rent_price = model.predict(prediction_square_feet)

In [64]:
prediction_rent_price

array([22260.88560886])